### PR TITLE
Override ldproxy install without prompting

### PR DESCRIPTION
**Pull request by UnTraDe**
When running this action again on the same runner, it fails when unzipping `ldproxy` because it asks if it should override existing file: 
image

This PR just adds the `-o` flag to the `unzip` command, telling it to overwrite without prompting.

### CODE REVIEW

**Review by SergioGasquez — APPROVED** [review]
Thanks! Changes LGTM! Mind rebasing so we can get CI green?

**Review by jessebraham — APPROVED** [review]
Thanks!

**Comment by UnTraDe** [comment]
Thanks!
Any plans to release a new version soon? I prefer to use `uses: esp-rs/xtensa-toolchain@v1.5.x` instead of `uses: esp-rs/xtensa-toolchain@main` :)

**Comment by SergioGasquez** [comment]
Just released `v1.5.3` and also updated the `v1.5` tag!

**Pull request merged**
